# Week 04 — Day 22: Data QA completeness checks on real Slovenian power data

Goal: verify whether the curated datasets are complete, consistent, and safe for analysis.

This notebook checks:
- file loading and timestamp parsing,
- dataset coverage,
- duplicate timestamps,
- null values,
- missing intervals,
- DST behavior,
- settlement-type structure,
- value ranges,
- known DA + imbalance timestamp mismatches.

In [3]:
# Import core libraries for data loading, timestamp checks, and QA summaries.
from pathlib import Path
import pandas as pd
import numpy as np

In [4]:
# Set display options so QA tables are easier to inspect in the notebook.
pd.set_option("display.max_columns", 120)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 200)

In [5]:
# Define the curated data folder.
# This notebook assumes all curated files are stored in the top-level data/curated folder.

DATA_DIR = Path("../data/curated")

# Define all datasets used in Day 22 QA.
# The config keeps the notebook reusable: if a new Slovenian power dataset is added later,
# add it here with its file name, timestamp column, and basic QA rules.

DATASET_CONFIG = {
    "da_2025": {
        "file": DATA_DIR / "da_prices_si_2025_clean.csv",
        "timestamp_col": "timestamp",
        "price_columns": ["price_eur_mwh"],
        "important_columns": ["price_eur_mwh"],
        "mtu_rules": [
            {"start": None, "end": "2025-10-01", "mtu_minutes": 60},
            {"start": "2025-10-01", "end": None, "mtu_minutes": 15},
        ],
        "interval_count_method": "rows",
    },
    "da_2026": {
        "file": DATA_DIR / "da_prices_si_clean.csv",
        "timestamp_col": "timestamp",
        "price_columns": ["price_eur_mwh"],
        "important_columns": ["price_eur_mwh"],
        "mtu_rules": [
            {"start": None, "end": None, "mtu_minutes": 15},
        ],
        "interval_count_method": "rows",
    },
    "imbalance": {
        "file": DATA_DIR / "imbalance_si_clean.csv",
        "timestamp_col": "timestamp",
        "price_columns": ["imbalance_price_pos", "imbalance_price_neg", "sipx"],
        "important_columns": ["imbalance_price_pos", "imbalance_price_neg", "sipx", "settlement_type"],
        "mtu_rules": [
            {"start": None, "end": None, "mtu_minutes": 15},
        ],
        "interval_count_method": "rows",
    },
    "balancing": {
        "file": DATA_DIR / "balancing_volumes_si_clean.csv",
        "timestamp_col": "timestamp",
        "price_columns": ["aFRR EUR/MWh", "mFRR EUR/MWh", "VoAA+ EUR/MWh", "VoAA- EUR/MWh"],
        "important_columns": ["Wpos MWh", "Wneg MWh", "Spos EUR", "Sneg EUR", "settlement_type"],
        "mtu_rules": [
            {"start": None, "end": None, "mtu_minutes": 15},
        ],
        # Balancing may contain more than one row per timestamp because of settlement_type.
        # For interval completeness, unique timestamps are more useful than raw row count.
        "interval_count_method": "unique_timestamps",
    },
}

## QA context

The Slovenian DA price data has an important market-structure feature:

- before 2025-10-01: 60-minute MTU,
- from 2025-10-01 onward: 15-minute MTU.

This mixed resolution in the 2025 DA file is expected and is not treated as a data-quality problem.

The Borzen datasets contain settlement data and may require checking `timestamp + settlement_type`, not timestamp alone.

DST expectations:

| Day type | 60-min MTU | 15-min MTU |
|---|---:|---:|
| Normal day | 24 | 96 |
| Spring DST day | 23 | 92 |
| Autumn DST day | 25 | 100 |

In [6]:
# Define helper functions for Slovenian power-market QA.
# These functions make the notebook reusable for other local power datasets.

def last_sunday(year: int, month: int) -> pd.Timestamp:
    """Return the last Sunday of a given month."""
    last_day = pd.Timestamp(year=year, month=month, day=1) + pd.offsets.MonthEnd(0)
    return last_day - pd.Timedelta(days=(last_day.weekday() + 1) % 7)


def is_spring_dst_day(date_value) -> bool:
    """Check whether a date is the spring DST transition day in Europe/Ljubljana."""
    date_value = pd.Timestamp(date_value)
    return date_value.normalize() == last_sunday(date_value.year, 3).normalize()


def is_autumn_dst_day(date_value) -> bool:
    """Check whether a date is the autumn DST transition day in Europe/Ljubljana."""
    date_value = pd.Timestamp(date_value)
    return date_value.normalize() == last_sunday(date_value.year, 10).normalize()


def dst_day_type(date_value) -> str:
    """Classify a date as normal, spring DST, or autumn DST."""
    if is_spring_dst_day(date_value):
        return "spring_dst_day"
    if is_autumn_dst_day(date_value):
        return "autumn_dst_day"
    return "normal_day"


def expected_market_intervals(date_value, mtu_minutes: int) -> int:
    """Return expected number of market intervals for a date and MTU."""
    normal_intervals = int(24 * 60 / mtu_minutes)
    intervals_per_hour = int(60 / mtu_minutes)

    if is_spring_dst_day(date_value):
        return normal_intervals - intervals_per_hour

    if is_autumn_dst_day(date_value):
        return normal_intervals + intervals_per_hour

    return normal_intervals


def assign_mtu_minutes(df: pd.DataFrame, mtu_rules: list, timestamp_col: str = "timestamp") -> pd.Series:
    """Assign MTU minutes to each row based on timestamp and configured MTU rules."""
    mtu = pd.Series(index=df.index, dtype="float64")

    for rule in mtu_rules:
        start = pd.Timestamp(rule["start"]) if rule["start"] is not None else None
        end = pd.Timestamp(rule["end"]) if rule["end"] is not None else None
        mtu_minutes = rule["mtu_minutes"]

        mask = pd.Series(True, index=df.index)

        if start is not None:
            mask = mask & (df[timestamp_col] >= start)

        if end is not None:
            mask = mask & (df[timestamp_col] < end)

        mtu.loc[mask] = mtu_minutes

    return mtu.astype("Int64")


def expected_timestamp_occurrences_for_day(date_value, mtu_minutes: int) -> pd.DataFrame:
    """
    Build expected timestamp labels for one delivery day.

    For spring DST, the 02:00 hour is skipped.
    For autumn DST, the 02:00 hour appears twice in local time.
    """
    date_value = pd.Timestamp(date_value).normalize()
    freq = f"{mtu_minutes}min"

    base_times = pd.date_range(
        start=date_value,
        end=date_value + pd.Timedelta(days=1),
        freq=freq,
        inclusive="left"
    )

    expected_times = pd.DataFrame({"timestamp": base_times})

    if is_spring_dst_day(date_value):
        expected_times = expected_times[expected_times["timestamp"].dt.hour != 2]

    if is_autumn_dst_day(date_value):
        repeated_hour = expected_times[expected_times["timestamp"].dt.hour == 2].copy()
        expected_times = pd.concat([expected_times, repeated_hour], ignore_index=True)

    expected_counts = (
        expected_times
        .value_counts("timestamp")
        .reset_index(name="expected_occurrences")
        .sort_values("timestamp")
        .reset_index(drop=True)
    )

    return expected_counts


def classify_completeness_reason(date_value, interval_count: int, expected_count: int) -> str:
    """Create a readable completeness label for a delivery day."""
    day_type = dst_day_type(date_value)

    if interval_count == expected_count:
        return f"complete_{day_type}"

    if interval_count < expected_count:
        return f"incomplete_{day_type}"

    return f"extra_intervals_{day_type}"

In [7]:
# Check that all configured files exist before loading.
# This prevents silent path or filename errors.

for dataset_name, config in DATASET_CONFIG.items():
    file_path = config["file"]
    print(dataset_name, "| exists:", file_path.exists(), "|", file_path)

da_2025 | exists: True | ..\data\curated\da_prices_si_2025_clean.csv
da_2026 | exists: True | ..\data\curated\da_prices_si_clean.csv
imbalance | exists: True | ..\data\curated\imbalance_si_clean.csv
balancing | exists: True | ..\data\curated\balancing_volumes_si_clean.csv

In [8]:
# Load each curated CSV into a separate dataframe.
# Each dataset is kept separate because Day 22 QA must identify issues per source file.

datasets = {}

for dataset_name, config in DATASET_CONFIG.items():
    file_path = config["file"]
    timestamp_col = config["timestamp_col"]

    df = pd.read_csv(file_path, parse_dates=[timestamp_col])

    # Standardize timestamp column name to "timestamp" for reusable QA functions.
    if timestamp_col != "timestamp":
        df = df.rename(columns={timestamp_col: "timestamp"})

    df = df.sort_values("timestamp").reset_index(drop=True)

    datasets[dataset_name] = df

    print(f"{dataset_name}: {df.shape[0]} rows, {df.shape[1]} columns")

da_2025: 15387 rows, 2 columns
da_2026: 8541 rows, 2 columns
imbalance: 11520 rows, 5 columns
balancing: 20160 rows, 66 columns

In [9]:
# Show columns, data types, first timestamp, and last timestamp for each dataset.
# This confirms whether timestamp parsing worked correctly and whether the files are readable.

for dataset_name, df in datasets.items():
    print("=" * 100)
    print(dataset_name)
    print("- rows/columns:", df.shape)
    print("- first timestamp:", df["timestamp"].min())
    print("- last timestamp:", df["timestamp"].max())
    print("- columns:", list(df.columns))
    print("- dtypes:")
    print(df.dtypes)
    print("- first 3 rows:")
    display(df.head(3))

====================================================================================================
da_2025
- rows/columns: (15387, 2)
- first timestamp: 2025-01-01 00:00:00
- last timestamp: 2026-01-01 00:00:00
- columns: ['timestamp', 'price_eur_mwh']
- dtypes:
timestamp        datetime64[us]
price_eur_mwh           float64
dtype: object
- first 3 rows:

            timestamp  price_eur_mwh
0 2025-01-01 00:00:00         118.46
1 2025-01-01 01:00:00         129.07
2 2025-01-01 02:00:00         121.10

====================================================================================================
da_2026
- rows/columns: (8541, 2)
- first timestamp: 2026-01-01 00:00:00
- last timestamp: 2026-04-01 00:00:00
- columns: ['timestamp', 'price_eur_mwh']
- dtypes:
timestamp        datetime64[us]
price_eur_mwh           float64
dtype: object
- first 3 rows:

            timestamp  price_eur_mwh
0 2026-01-01 00:00:00         100.51
1 2026-01-01 00:15:00          94.03
2 2026-01-01 00:30:00          92.01

====================================================================================================
imbalance
- rows/columns: (11520, 5)
- first timestamp: 2025-11-01 00:15:00
- last timestamp: 2026-03-01 00:00:00
- columns: ['timestamp', 'imbalance_price_pos', 'imbalance_price_neg', 'sipx', 'settlement_type']
- dtypes:
timestamp              datetime64[us]
imbalance_price_pos           float64
imbalance_price_neg           float64
sipx                          float64
settlement_type                   str
dtype: object
- first 3 rows:

            timestamp  imbalance_price_pos  imbalance_price_neg    sipx              settlement_type
0 2025-11-01 00:15:00                20.71                20.71  103.63  Second imbalance settlement
1 2025-11-01 00:30:00                20.33                20.33  106.03  Second imbalance settlement
2 2025-11-01 00:45:00                20.94                20.94   85.55  Second imbalance settlement

====================================================================================================
balancing
- rows/columns: (20160, 66)
- first timestamp: 2025-11-01 00:15:00
- last timestamp: 2026-03-01 00:00:00
- columns: ['timestamp', 'Wpos MWh', 'Wneg MWh', 'Spos EUR', 'Sneg EUR', "WpozFCR_Q' MWh", "WnegFCR_Q' MWh", 'aRPF+akt (aFRR+act) MWh MWh', 'aFRR MWh', 'aFRR EUR', 'aFRR EUR/MWh', 'aRPF-akt (aFRR-act) MWh MWh', 'naFRR MWh', 'naFRR EUR', 'naFRR EUR/MWh', 'mFRR MWh', 'mFRR EUR', 'mFRR EUR/MWh', 'nmFRR  MWh', 'nmFRR  EUR', 'nmFRR  EUR/MWh', 'RR MWh', 'RR EUR', 'RR EUR/MWh', 'nRR MWh', 'nRR EUR', 'nRR EUR/MWh', 'IGCC (pos) MWh', 'IGCC (pos) EUR', 'IGCC (pos) EUR/MWh', 'IGCC (neg) MWh', 'IGCC (neg) EUR', 'IGCC (neg) EUR/MWh', 'VoAA+ EUR/MWh', 'VoAA- EUR/MWh', 'WnegFSkar MWh', 'FSkar (pos) MWh', 'SnegFSkar EUR', 'SpozFSkar EUR', 'Inbalance BS W+ MWh', 'Inbalance BS W- MWh', 'aFRR+ akt TUJ>SI EUR EUR', 'aFRR- akt TUJ>SI EUR EUR', 'aFRR+ akt TUJ>SII MWh MWh', 'aFRR- akt TUJ>SI MWh MWh', 'aFRR+ akt SI>SI EUR EUR', 'aFRR- akt SI>SI EUR EUR', 'aFRR+ akt SI>SI MWh MWh', 'aFRR- akt SI>SI MWh MWh', 'mFRR+ akt TUJ>SI  EUR EUR', 'mFRR- akt TUJ>SI  EUR EUR', 'mFRR+ akt TUJ>SI  MWh MWh', 'mFRR- akt TUJ>SI  MWh MWh', 'mFRR+ akt SI>SI  EUR EUR', 'mFRR- akt SI>SI  EUR EUR', 'mFRR+ akt SI>SI  MWh MWh', 'mFRR- akt SI>SI  MWh MWh', 'QWpozVTL_NOS_Q MWh', 'QWnegVTL_NOS_Q MWh', 'QWpozVTL_HOPS_Q MWh', 'QWnegVTL_HOPS_Q MWh', 'QWpozVTL_PICASSO_Q MWh', 'QWnegVTL_PICASSO_Q MWh', 'QWpozVTL_MARI_Q MWh', 'QWnegVTL_MARI_Q MWh', 'settlement_type']
- dtypes:
timestamp                      datetime64[us]
Wpos MWh                              float64
Wneg MWh                              float64
Spos EUR                              float64
Sneg EUR                              float64
WpozFCR_Q' MWh                        float64
WnegFCR_Q' MWh                        float64
aRPF+akt (aFRR+act) MWh MWh           float64
aFRR MWh                              float64
aFRR EUR                              float64
aFRR EUR/MWh                          float64
aRPF-akt (aFRR-act) MWh MWh           float64
naFRR MWh                             float64
naFRR EUR                             float64
naFRR EUR/MWh                         float64
mFRR MWh                              float64
mFRR EUR                              float64
mFRR EUR/MWh                          float64
nmFRR  MWh                            float64
nmFRR  EUR                            float64
nmFRR  EUR/MWh                        float64
RR MWh                                float64
RR EUR                                float64
RR EUR/MWh                            float64
nRR MWh                               float64
nRR EUR                               float64
nRR EUR/MWh                           float64
IGCC (pos) MWh                        float64
IGCC (pos) EUR                        float64
IGCC (pos) EUR/MWh                    float64
IGCC (neg) MWh                        float64
IGCC (neg) EUR                        float64
IGCC (neg) EUR/MWh                    float64
VoAA+ EUR/MWh                         float64
VoAA- EUR/MWh                         float64
WnegFSkar MWh                         float64
FSkar (pos) MWh                       float64
SnegFSkar EUR                         float64
SpozFSkar EUR                         float64
Inbalance BS W+ MWh                   float64
Inbalance BS W- MWh                   float64
aFRR+ akt TUJ>SI EUR EUR              float64
aFRR- akt TUJ>SI EUR EUR              float64
aFRR+ akt TUJ>SII MWh MWh             float64
aFRR- akt TUJ>SI MWh MWh              float64
aFRR+ akt SI>SI EUR EUR               float64
aFRR- akt SI>SI EUR EUR               float64
aFRR+ akt SI>SI MWh MWh               float64
aFRR- akt SI>SI MWh MWh               float64
mFRR+ akt TUJ>SI  EUR EUR             float64
mFRR- akt TUJ>SI  EUR EUR             float64
mFRR+ akt TUJ>SI  MWh MWh             float64
mFRR- akt TUJ>SI  MWh MWh             float64
mFRR+ akt SI>SI  EUR EUR              float64
mFRR- akt SI>SI  EUR EUR              float64
mFRR+ akt SI>SI  MWh MWh              float64
mFRR- akt SI>SI  MWh MWh              float64
QWpozVTL_NOS_Q MWh                    float64
QWnegVTL_NOS_Q MWh                    float64
QWpozVTL_HOPS_Q MWh                   float64
QWnegVTL_HOPS_Q MWh                   float64
QWpozVTL_PICASSO_Q MWh                float64
QWnegVTL_PICASSO_Q MWh                float64
QWpozVTL_MARI_Q MWh                   float64
QWnegVTL_MARI_Q MWh                   float64
settlement_type                           str
dtype: object
- first 3 rows:

,timestamp,Wpos MWh,Wneg MWh,Spos EUR,Sneg EUR,WpozFCR_Q' MWh,WnegFCR_Q' MWh,aRPF+akt (aFRR+act) MWh MWh,aFRR MWh,aFRR EUR,aFRR EUR/MWh,aRPF-akt (aFRR-act) MWh MWh,naFRR MWh,naFRR EUR,naFRR EUR/MWh,mFRR MWh,mFRR EUR,mFRR EUR/MWh,nmFRR MWh,nmFRR EUR,nmFRR EUR/MWh,RR MWh,RR EUR,RR EUR/MWh,nRR MWh,nRR EUR,nRR EUR/MWh,IGCC (pos) MWh,IGCC (pos) EUR,IGCC (pos) EUR/MWh,IGCC (neg) MWh,IGCC (neg) EUR,IGCC (neg) EUR/MWh,VoAA+ EUR/MWh,VoAA- EUR/MWh,WnegFSkar MWh,FSkar (pos) MWh,SnegFSkar EUR,SpozFSkar EUR,Inbalance BS W+ MWh,Inbalance BS W- MWh,aFRR+ akt TUJ>SI EUR EUR,aFRR- akt TUJ>SI EUR EUR,aFRR+ akt TUJ>SII MWh MWh,aFRR- akt TUJ>SI MWh MWh,aFRR+ akt SI>SI EUR EUR,aFRR- akt SI>SI EUR EUR,aFRR+ akt SI>SI MWh MWh,aFRR- akt SI>SI MWh MWh,mFRR+ akt TUJ>SI EUR EUR,mFRR- akt TUJ>SI EUR EUR,mFRR+ akt TUJ>SI MWh MWh,mFRR- akt TUJ>SI MWh MWh,mFRR+ akt SI>SI EUR EUR,mFRR- akt SI>SI EUR EUR,mFRR+ akt SI>SI MWh MWh,mFRR- akt SI>SI MWh MWh,QWpozVTL_NOS_Q MWh,QWnegVTL_NOS_Q MWh,QWpozVTL_HOPS_Q MWh,QWnegVTL_HOPS_Q MWh,QWpozVTL_PICASSO_Q MWh,QWnegVTL_PICASSO_Q MWh,QWpozVTL_MARI_Q MWh,QWnegVTL_MARI_Q MWh,settlement_type
0,2025-11-01 00:15:00,0.010,-20.263,1.54,-795.50,0.041,-0.002,0.01,0.01,1.54,154.0,-1.045,-0.918,-19.01,20.71,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.00,-17.111,-734.57,42.93,0.0,0.0,-2.234,0.000,-41.92,0.00,27.106,-6.763,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
1,2025-11-01 00:30:00,0.200,-22.249,12.49,-798.75,0.011,-0.012,0.00,0.00,0.00,0.0,-2.589,-2.511,-51.06,20.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.00,-19.001,-737.58,38.82,0.0,0.0,-0.737,0.200,-10.11,12.49,24.635,-2.507,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
2,2025-11-01 00:45:00,1.119,-10.075,61.84,-281.16,0.018,-0.012,0.00,0.00,0.00,0.0,-0.853,-0.780,-16.33,20.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.045,2.21,49.11,-9.093,-249.87,27.48,0.0,0.0,-0.202,1.074,-14.96,59.63,13.439,-4.415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement

In [10]:
# Create a compact QA summary for each dataset.
# This checks coverage, duplicate timestamps, and total null values.

coverage_summary = []

for dataset_name, df in datasets.items():
    coverage_summary.append({
        "dataset": dataset_name,
        "rows": len(df),
        "columns": len(df.columns),
        "first_timestamp": df["timestamp"].min(),
        "last_timestamp": df["timestamp"].max(),
        "duplicate_timestamps": df["timestamp"].duplicated().sum(),
        "total_null_values": df.isna().sum().sum(),
    })

coverage_summary_df = pd.DataFrame(coverage_summary)

display(coverage_summary_df)

     dataset   rows  columns     first_timestamp last_timestamp  duplicate_timestamps  total_null_values
0    da_2025  15387        2 2025-01-01 00:00:00     2026-01-01                     4                  0
1    da_2026   8541        2 2026-01-01 00:00:00     2026-04-01                     0                  0
2  imbalance  11520        5 2025-11-01 00:15:00     2026-03-01                     0                  0
3  balancing  20160       66 2025-11-01 00:15:00     2026-03-01                  8640                  0

## Initial QA coverage finding

The curated datasets were loaded successfully and timestamps were parsed as datetime.

This first QA table checks:
- row count,
- column count,
- time coverage,
- duplicate timestamps,
- total null values.

This does not yet prove full completeness. It only confirms that the datasets are structurally usable for deeper QA checks.

In [11]:
# Check duplicate timestamps and duplicate timestamp + settlement_type combinations.
# This separates true duplicate problems from expected settlement-data structure.

duplicate_summary = []

for dataset_name, df in datasets.items():
    row = {
        "dataset": dataset_name,
        "rows": len(df),
        "duplicate_timestamps": df["timestamp"].duplicated().sum(),
    }

    if "settlement_type" in df.columns:
        row["duplicate_timestamp_settlement_type"] = df.duplicated(
            subset=["timestamp", "settlement_type"]
        ).sum()
    else:
        row["duplicate_timestamp_settlement_type"] = np.nan

    duplicate_summary.append(row)

duplicate_summary_df = pd.DataFrame(duplicate_summary)

display(duplicate_summary_df)

     dataset   rows  duplicate_timestamps  duplicate_timestamp_settlement_type
0    da_2025  15387                     4                                  NaN
1    da_2026   8541                     0                                  NaN
2  imbalance  11520                     0                                  0.0
3  balancing  20160                  8640                               8640.0

In [12]:
# Inspect duplicate timestamp rows only where duplicates exist.
# For DA 2025, duplicates are likely related to the autumn DST repeated hour.
# For balancing, duplicates may be explained by settlement_type.

for dataset_name, df in datasets.items():
    duplicate_rows = (
        df[df["timestamp"].duplicated(keep=False)]
        .sort_values("timestamp")
        .reset_index(drop=True)
    )

    if len(duplicate_rows) > 0:
        print("=" * 100)
        print(dataset_name)
        print("Duplicate timestamp rows:", len(duplicate_rows))
        print("Unique duplicated timestamps:", duplicate_rows["timestamp"].nunique())
        display(duplicate_rows.head(40))

====================================================================================================
da_2025
Duplicate timestamp rows: 8
Unique duplicated timestamps: 4

            timestamp  price_eur_mwh
0 2025-10-26 02:00:00          75.33
1 2025-10-26 02:00:00          63.05
2 2025-10-26 02:15:00          67.41
3 2025-10-26 02:15:00          65.54
4 2025-10-26 02:30:00          60.01
5 2025-10-26 02:30:00          63.93
6 2025-10-26 02:45:00          53.67
7 2025-10-26 02:45:00          58.91

====================================================================================================
balancing
Duplicate timestamp rows: 17280
Unique duplicated timestamps: 8640

,timestamp,Wpos MWh,Wneg MWh,Spos EUR,Sneg EUR,WpozFCR_Q' MWh,WnegFCR_Q' MWh,aRPF+akt (aFRR+act) MWh MWh,aFRR MWh,aFRR EUR,aFRR EUR/MWh,aRPF-akt (aFRR-act) MWh MWh,naFRR MWh,naFRR EUR,naFRR EUR/MWh,mFRR MWh,mFRR EUR,mFRR EUR/MWh,nmFRR MWh,nmFRR EUR,nmFRR EUR/MWh,RR MWh,RR EUR,RR EUR/MWh,nRR MWh,nRR EUR,nRR EUR/MWh,IGCC (pos) MWh,IGCC (pos) EUR,IGCC (pos) EUR/MWh,IGCC (neg) MWh,IGCC (neg) EUR,IGCC (neg) EUR/MWh,VoAA+ EUR/MWh,VoAA- EUR/MWh,WnegFSkar MWh,FSkar (pos) MWh,SnegFSkar EUR,SpozFSkar EUR,Inbalance BS W+ MWh,Inbalance BS W- MWh,aFRR+ akt TUJ>SI EUR EUR,aFRR- akt TUJ>SI EUR EUR,aFRR+ akt TUJ>SII MWh MWh,aFRR- akt TUJ>SI MWh MWh,aFRR+ akt SI>SI EUR EUR,aFRR- akt SI>SI EUR EUR,aFRR+ akt SI>SI MWh MWh,aFRR- akt SI>SI MWh MWh,mFRR+ akt TUJ>SI EUR EUR,mFRR- akt TUJ>SI EUR EUR,mFRR+ akt TUJ>SI MWh MWh,mFRR- akt TUJ>SI MWh MWh,mFRR+ akt SI>SI EUR EUR,mFRR- akt SI>SI EUR EUR,mFRR+ akt SI>SI MWh MWh,mFRR- akt SI>SI MWh MWh,QWpozVTL_NOS_Q MWh,QWnegVTL_NOS_Q MWh,QWpozVTL_HOPS_Q MWh,QWnegVTL_HOPS_Q MWh,QWpozVTL_PICASSO_Q MWh,QWnegVTL_PICASSO_Q MWh,QWpozVTL_MARI_Q MWh,QWnegVTL_MARI_Q MWh,settlement_type
0,2025-12-01 00:15:00,2.287,-18.030,208.94,-633.84,0.000,0.000,0.000,0.000,0.00,0.00,-2.928,-2.721,-91.37,33.58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.039,1.31,33.59,-11.415,-528.06,46.26,0.0,0.0,-3.894,2.248,-14.41,207.63,22.106,-6.180,0.0,0.0,0.0,0.0,0.00,-91.37,0.000,-2.721,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
1,2025-12-01 00:15:00,2.287,-18.030,208.94,-633.84,0.000,0.000,0.000,0.000,0.00,0.00,-2.928,-2.721,-91.37,33.58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.039,1.31,33.59,-11.415,-528.06,46.26,0.0,0.0,-3.894,2.248,-14.41,207.63,22.106,-6.180,0.0,0.0,0.0,0.0,0.00,-91.37,0.000,-2.721,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
2,2025-12-01 00:30:00,2.405,-3.077,129.54,-228.36,0.000,0.000,0.065,0.065,10.07,154.92,-0.164,-0.164,-5.54,33.78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.708,23.91,33.77,-2.897,-221.34,76.40,0.0,0.0,-0.016,1.632,-1.48,95.56,7.807,-7.115,0.0,0.0,0.0,0.0,10.07,-5.54,0.065,-0.164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
3,2025-12-01 00:30:00,2.405,-3.077,129.54,-228.36,0.000,0.000,0.065,0.065,10.07,154.92,-0.164,-0.164,-5.54,33.78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.708,23.91,33.77,-2.897,-221.34,76.40,0.0,0.0,-0.016,1.632,-1.48,95.56,7.807,-7.115,0.0,0.0,0.0,0.0,10.07,-5.54,0.065,-0.164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
4,2025-12-01 00:45:00,1.103,-4.410,64.00,-261.33,0.000,0.000,0.100,0.100,15.45,154.50,-1.151,-0.988,-33.26,33.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.215,7.24,33.67,-3.422,-228.07,66.65,0.0,0.0,0.000,0.788,0.00,41.31,13.123,-9.672,0.0,0.0,0.0,0.0,15.45,-33.26,0.100,-0.988,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
5,2025-12-01 00:45:00,1.103,-4.410,64.00,-261.33,0.000,0.000,0.100,0.100,15.45,154.50,-1.151,-0.988,-33.26,33.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.215,7.24,33.67,-3.422,-228.07,66.65,0.0,0.0,0.000,0.788,0.00,41.31,13.123,-9.672,0.0,0.0,0.0,0.0,15.45,-33.26,0.100,-0.988,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
6,2025-12-01 01:00:00,1.455,-4.339,122.34,-185.75,0.000,0.000,0.000,0.000,0.00,0.00,-1.958,-1.760,-59.38,33.74,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.256,10.87,42.46,-2.523,-126.37,50.09,0.0,0.0,-0.056,1.199,0.00,111.47,13.150,-10.074,0.0,0.0,0.0,0.0,0.00,-59.38,0.000,-1.760,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
7,2025-12-01 01:00:00,1.455,-4.339,122.34,-185.75,0.000,0.000,0.000,0.000,0.00,0.00,-1.958,-1.760,-59.38,33.74,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.256,10.87,42.46,-2.523,-126.37,50.09,0.0,0.0,-0.056,1.199,0.00,111.47,13.150,-10.074,0.0,0.0,0.0,0.0,0.00,-59.38,0.000,-1.760,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
8,2025-12-01 01:15:00,4.080,-4.044,238.89,-181.92,0.000,0.000,0.000,0.000,0.00,0.00,-1.314,-1.152,-38.75,33.64,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.095,37.59,34.33,-2.639,-122.52,46.43,0.0,0.0,-0.253,2.985,-20.65,201.30,11.958,-11.846,0.0,0.0,0.0,0.0,0.00,-38.75,0.000,-1.152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
9,2025-12-01 01:15:00,4.080,-4.044,238.89,-181.92,0.000,0.000,0.000,0.000,0.00,0.00,-1.314,-1.152,-38.75,33.64,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.095,37.59,34.33,-2.639,-122.52,46.43,0.0,0.0,-0.253,2.985,-20.65,201.30,11.958,-11.846,0.0,0.0,0.0,0.0,0.00,-38.75,0.000,-1.152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
10,2025-12-01 01:30:00,0.887,-3.685,18.32,-191.43,0.000,0.000,0.079,0.079,12.08,152.91,-0.880,-0.799,-26.74,33.47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.704,-3.07,-4.36,-2.283,-111.60,48.88,0.0,0.0,-0.603,0.104,-53.09,9.31,9.064,-6.179,0.0,0.0,0.0,0.0,12.08,-26.74,0.079,-0.799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
11,2025-12-01 01:30:00,0.887,-3.685,18.32,-191.43,0.000,0.000,0.079,0.079,12.08,152.91,-0.880,-0.799,-26.74,33.47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.704,-3.07,-4.36,-2.283,-111.60,48.88,0.0,0.0,-0.603,0.104,-53.09,9.31,9.064,-6.179,0.0,0.0,0.0,0.0,12.08,-26.74,0.079,-0.799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
12,2025-12-01 01:45:00,2.889,-5.276,191.27,-272.59,0.000,0.000,0.160,0.147,22.46,152.79,-0.874,-0.775,-26.00,33.55,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.273,43.72,34.34,-4.213,-243.52,57.80,0.0,0.0,-0.288,1.469,-3.07,125.09,9.061,-6.590,0.0,0.0,0.0,0.0,22.46,-26.00,0.147,-0.775,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
13,2025-12-01 01:45:00,2.889,-5.276,191.27,-272.59,0.000,0.000,0.160,0.147,22.46,152.79,-0.874,-0.775,-26.00,33.55,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.273,43.72,34.34,-4.213,-243.52,57.80,0.0,0.0,-0.288,1.469,-3.07,125.09,9.061,-6.590,0.0,0.0,0.0,0.0,22.46,-26.00,0.147,-0.775,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
14,2025-12-01 02:00:00,4.546,-2.809,81.82,-197.88,0.000,0.000,0.262,0.262,40.04,152.82,-0.658,-0.523,-17.45,33.37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.700,25.99,37.13,-1.813,-144.01,79.43,0.0,0.0,-0.473,3.584,-36.42,15.79,6.352,-7.936,0.0,0.0,0.0,0.0,40.04,-17.45,0.262,-0.523,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
15,2025-12-01 02:00:00,4.546,-2.809,81.82,-197.88,0.000,0.000,0.262,0.262,40.04,152.82,-0.658,-0.523,-17.45,33.37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.700,25.99,37.13,-1.813,-144.01,79.43,0.0,0.0,-0.473,3.584,-36.42,15.79,6.352,-7.936,0.0,0.0,0.0,0.0,40.04,-17.45,0.262,-0.523,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
16,2025-12-01 02:15:00,3.450,-10.956,180.85,-270.95,0.000,0.000,0.000,0.000,0.00,0.00,-6.063,-5.841,-179.98,30.81,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.389,43.05,30.99,-1.614,-89.63,55.53,0.0,0.0,-3.501,2.061,-1.34,137.80,12.141,-4.435,0.0,0.0,0.0,0.0,0.00,-179.98,0.000,-5.841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
17,2025-12-01 02:15:00,3.450,-10.956,180.85,-270.95,0.000,0.000,0.000,0.000,0.00,0.00,-6.063,-5.841,-179.98,30.81,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.389,43.05,30.99,-1.614,-89.63,55.53,0.0,0.0,-3.501,2.061,-1.34,137.80,12.141,-4.435,0.0,0.0,0.0,0.0,0.00,-179.98,0.000,-5.841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
18,2025-12-01 02:30:00,2.357,-4.192,121.68,-141.67,0.000,0.000,0.002,0.002,0.33,165.00,-2.499,-2.335,-76.23,32.65,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.505,10.50,20.79,-1.828,-63.25,34.60,0.0,0.0,-0.029,1.850,-2.19,110.85,6.929,-4.918,0.0,0.0,0.0,0.0,0.33,-76.23,0.002,-2.335,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
19,2025-12-01 02:30:00,2.357,-4.192,121.68,-141.67,0.000,0.000,0.002,0.002,0.33,165.00,-2.499,-2.335,-76.23,32.65,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.505,10.50,20.79,-1.828,-63.25,34.60,0.0,0.0,-0.029,1.850,-2.19,110.85,6.929,-4.918,0.0,0.0,0.0,0.0,0.33,-76.23,0.002,-2.335,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
20,2025-12-01 02:45:00,3.054,-3.455,152.61,-100.36,0.000,0.000,0.000,0.000,0.00,0.00,-2.696,-2.514,-81.65,32.48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.296,92.22,40.17,-0.433,-18.71,43.21,0.0,0.0,-0.508,0.758,0.00,60.39,4.662,-4.097,0.0,0.0,0.0,0.0,0.00,-81.65,0.000,-2.514,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
21,2025-12-01 02:45:00,3.054,-3.455,152.61,-100.36,0.000,0.000,0.000,0.000,0.00,0.00,-2.696,-2.514,-81.65,32.48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.296,92.22,40.17,-0.433,-18.71,43.21,0.0,0.0,-0.508,0.758,0.00,60.39,4.662,-4.097,0.0,0.0,0.0,0.0,0.00,-81.65,0.000,-2.514,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
22,2025-12-01 03:00:00,4.117,-2.246,212.69,-82.54,0.000,0.000,0.000,0.000,0.00,0.00,-1.071,-0.910,-30.01,32.98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.146,71.88,33.49,-1.238,-48.96,39.55,0.0,0.0,-0.098,1.971,-3.57,140.81,5.664,-7.379,0.0,0.0,0.0,0.0,0.00,-30.01,0.000,-0.910,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
23,2025-12-01 03:00:00,4.117,-2.246,212.69,-82.54,0.000,0.000,0.000,0.000,0.00,0.00,-1.071,-0.910,-30.01,32.98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.146,71.88,33.49,-1.238,-48.96,39.55,0.0,0.0,-0.098,1.971,-3.57,140.81,5.664,-7.379,0.0,0.0,0.0,0.0,0.00,-30.01,0.000,-0.910,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
24,2025-12-01 03:15:00,3.503,-1.935,249.16,-100.04,0.000,0.000,0.937,0.937,143.04,152.66,-0.009,-0.001,-0.03,30.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.467,46.56,31.74,-1.904,-97.87,51.40,0.0,0.0,-0.030,1.099,-2.14,59.56,6.954,-8.512,0.0,0.0,0.0,0.0,143.04,-0.03,0.937,-0.001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
25,2025-12-01 03:15:00,3.503,-1.935,249.16,-100.04,0.000,0.000,0.937,0.937,143.04,152.66,-0.009,-0.001,-0.03,30.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.467,46.56,31.74,-1.904,-97.87,51.40,0.0,0.0,-0.030,1.099,-2.14,59.56,6.954,-8.512,0.0,0.0,0.0,0.0,143.04,-0.03,0.937,-0.001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
26,2025-12-01 03:30:00,1.540,-6.851,135.46,-397.27,0.000,0.000,0.576,0.564,83.91,148.78,-0.018,-0.017,-0.56,32.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.534,17.60,32.96,-6.788,-396.71,58.44,0.0,0.0,-0.046,0.442,0.00,33.95,11.116,-5.806,0.0,0.0,0.0,0.0,83.91,-0.56,0.564,-0.017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
27,2025-12-01 03:30:00,1.540,-6.851,135.46,-397.27,0.000,0.000,0.576,0.564,83.91,148.78,-0.018,-0.017,-0.56,32.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.534,17.60,32.96,-6.788,-396.71,58.44,0.0,0.0,-0.046,0.442,0.00,33.95,11.116,-5.806,0.0,0.0,0.0,0.0,83.91,-0.56,0.564,-0.017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
28,2025-12-01 03:45:00,6.644,-0.198,492.25,-9.44,0.000,0.000,1.705,1.586,247.19,155.86,0.000,0.000,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.321,112.61,33.91,-0.172,-7.41,43.08,0.0,0.0,-0.026,1.737,-2.03,132.45,4.667,-11.243,0.0,0.0,0.0,0.0,247.19,0.00,1.586,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
29,2025-12-01 03:45:00,6.644,-0.198,492.25,-9.44,0.000,0.000,1.705,1.586,247.19,155.86,0.000,0.000,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.321,112.61,33.91,-0.172,-7.41,43.08,0.0,0.0,-0.026,1.737,-2.03,132.45,4.667,-11.243,0.0,0.0,0.0,0.0,247.19,0.00,1.586,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
30,2025-12-01 04:00:00,4.472,-2.333,214.01,-116.58,0.000,0.000,0.643,0.643,96.43,149.97,-0.101,-0.085,-2.81,33.06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.106,110.72,35.65,-2.092,-100.88,48.22,0.0,0.0,-0.156,0.723,-12.89,6.86,3.940,-6.008,0.0,0.0,0.0,0.0,96.43,-2.81,0.643,-0.085,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
31,2025-12-01 04:00:00,4.472,-2.333,214.01,-116.58,0.000,0.000,0.643,0.643,96.43,149.97,-0.101,-0.085,-2.81,33.06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.106,110.72,35.65,-2.092,-100.88,48.22,0.0,0.0,-0.156,0.723,-12.89,6.86,3.940,-6.008,0.0,0.0,0.0,0.0,96.43,-2.81,0.643,-0.085,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
32,2025-12-01 04:15:00,4.365,-4.039,429.91,-204.23,0.068,0.000,1.442,1.380,231.37,167.66,-0.117,-0.117,-4.07,34.79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.860,29.90,34.77,-2.634,-176.83,67.13,0.0,0.0,-1.288,2.125,-23.33,168.64,4.981,-5.465,0.0,0.0,0.0,0.0,231.37,-4.07,1.380,-0.117,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
33,2025-12-01 04:15:00,4.365,-4.039,429.91,-204.23,0.068,0.000,1.442,1.380,231.37,167.66,-0.117,-0.117,-4.07,34.79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.860,29.90,34.77,-2.634,-176.83,67.13,0.0,0.0,-1.288,2.125,-23.33,168.64,4.981,-5.465,0.0,0.0,0.0,0.0,231.37,-4.07,1.380,-0.117,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
34,2025-12-01 04:30:00,2.029,-7.315,206.99,-434.98,0.029,-0.002,0.683,0.683,110.26,161.43,-0.033,-0.014,-0.49,35.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.189,6.63,35.08,-7.188,-424.88,59.11,0.0,0.0,-0.113,1.157,-9.61,90.10,10.883,-5.550,0.0,0.0,0.0,0.0,110.26,-0.49,0.683,-0.014,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
35,2025-12-01 04:30:00,2.029,-7.315,206.99,-434.98,0.029,-0.002,0.683,0.683,110.26,161.43,-0.033,-0.014,-0.49,35.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.189,6.63,35.08,-7.188,-424.88,59.11,0.0,0.0,-0.113,1.157,-9.61,90.10,10.883,-5.550,0.0,0.0,0.0,0.0,110.26,-0.49,0.683,-0.014,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
36,2025-12-01 04:45:00,2.050,-4.656,196.06,-323.00,0.033,-0.005,0.753,0.737,118.35,160.58,0.000,0.000,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.221,7.67,34.71,-4.542,-313.99,69.13,0.0,0.0,-0.114,1.092,-9.01,70.04,7.933,-5.427,0.0,0.0,0.0,0.0,118.35,0.00,0.737,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
37,2025-12-01 04:45:00,2.050,-4.656,196.06,-323.00,0.033,-0.005,0.753,0.737,118.35,160.58,0.000,0.000,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.221,7.67,34.71,-4.542,-313.99,69.13,0.0,0.0,-0.114,1.092,-9.01,70.04,7.933,-5.427,0.0,0.0,0.0,0.0,118.35,0.00,0.737,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
38,2025-12-01 05:00:00,2.893,-6.728,182.23,-186.31,0.014,-0.034,0.208,0.208,32.09,154.28,-0.527,-0.460,-15.67,34.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.573,55.87,35.52,-3.178,-170.64,53.69,0.0,0.0,-3.090,1.112,0.00,94.27,8.890,-4.958,0.0,0.0,0.0,0.0,32.09,-15.67,0.208,-0.460,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement
39,2025-12-01 05:00:00,2.893,-6.728,182.23,-186.31,0.014,-0.034,0.208,0.208,32.09,154.28,-0.527,-0.460,-15.67,34.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.573,55.87,35.52,-3.178,-170.64,53.69,0.0,0.0,-3.090,1.112,0.00,94.27,8.890,-4.958,0.0,0.0,0.0,0.0,32.09,-15.67,0.208,-0.460,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Second imbalance settlement

In [13]:
# Show settlement type counts for datasets that contain settlement_type.
# This is important for Borzen imbalance and balancing data.

for dataset_name, df in datasets.items():
    if "settlement_type" in df.columns:
        print("=" * 100)
        print(dataset_name)

        settlement_counts = (
            df["settlement_type"]
            .value_counts(dropna=False)
            .rename_axis("settlement_type")
            .reset_index(name="rows")
        )

        display(settlement_counts)

====================================================================================================
imbalance

               settlement_type  rows
0  Second imbalance settlement  8832
1   First imbalance settlement  2688

====================================================================================================
balancing

               settlement_type   rows
0  Second imbalance settlement  14784
1   First imbalance settlement   5376

## Duplicate and settlement-type finding

Duplicate timestamps must be interpreted by dataset.

For DA 2025, duplicate local timestamps are expected around the autumn DST transition, when the clock moves back and the 02:00 hour repeats.

For Borzen datasets, timestamp alone may not always be the correct uniqueness key because the data includes `settlement_type`.

Therefore:
- DA duplicate timestamps are checked against DST behavior.
- Borzen duplicate timestamps are checked against `timestamp + settlement_type`.

In [14]:
# Add MTU metadata to each dataset based on configured MTU rules.
# This is necessary because DA 2025 has mixed 60-minute and 15-minute resolution.

datasets_with_mtu = {}

for dataset_name, df in datasets.items():
    config = DATASET_CONFIG[dataset_name]

    df_mtu = df.copy()
    df_mtu["mtu_minutes"] = assign_mtu_minutes(
        df_mtu,
        mtu_rules=config["mtu_rules"],
        timestamp_col="timestamp"
    )

    df_mtu["delivery_date"] = df_mtu["timestamp"].dt.date

    datasets_with_mtu[dataset_name] = df_mtu

    print(dataset_name)
    display(
        df_mtu["mtu_minutes"]
        .value_counts(dropna=False)
        .rename_axis("mtu_minutes")
        .reset_index(name="rows")
    )

da_2025

   mtu_minutes  rows
0           15  8836
1           60  6551

da_2026

   mtu_minutes  rows
0           15  8541

imbalance

   mtu_minutes   rows
0           15  11520

balancing

   mtu_minutes   rows
0           15  20160

In [26]:
# Count expected intervals per delivery day and compare them with actual data.
# This is the core completeness check for Day 22.

daily_completeness_results = []

for dataset_name, df in datasets_with_mtu.items():
    df_check = df.copy()

    # Count raw rows per delivery day and MTU.
    # For DA and imbalance data, one row normally represents one market interval.
    row_counts = (
        df_check
        .groupby(["delivery_date", "mtu_minutes"])
        .size()
        .reset_index(name="row_count")
    )

    # Count unique timestamp labels per delivery day and MTU.
    # This is useful for datasets where one timestamp can appear multiple times,
    # for example balancing data with different settlement_type values.
    unique_timestamp_counts = (
        df_check
        .groupby(["delivery_date", "mtu_minutes"])["timestamp"]
        .nunique()
        .reset_index(name="unique_timestamp_count")
    )

    # Combine row count and unique timestamp count into one QA table.
    daily_counts = row_counts.merge(
        unique_timestamp_counts,
        on=["delivery_date", "mtu_minutes"],
        how="left"
    )

    daily_counts["dataset"] = dataset_name

    # Calculate expected market intervals based on MTU and DST day type.
    # 60-min normal day = 24
    # 60-min spring DST day = 23
    # 60-min autumn DST day = 25
    # 15-min normal day = 96
    # 15-min spring DST day = 92
    # 15-min autumn DST day = 100
    daily_counts["expected_intervals"] = daily_counts.apply(
        lambda row: expected_market_intervals(
            row["delivery_date"],
            int(row["mtu_minutes"])
        ),
        axis=1
    )

    # Add DST classification for easier interpretation.
    daily_counts["dst_day_type"] = daily_counts["delivery_date"].apply(dst_day_type)

    # Choose the correct actual interval count basis.
    # DA and imbalance: use row_count because each row is one market interval.
    # Balancing: use unique_timestamp_count because duplicate rows can exist due to settlement_type.
    if dataset_name == "balancing":
        daily_counts["actual_interval_count"] = daily_counts["unique_timestamp_count"]
        daily_counts["count_basis"] = "unique_timestamp_count"
    else:
        daily_counts["actual_interval_count"] = daily_counts["row_count"]
        daily_counts["count_basis"] = "row_count"

    # Compare actual interval count with expected interval count.
    daily_counts["is_complete_day"] = (
        daily_counts["actual_interval_count"] == daily_counts["expected_intervals"]
    )

    daily_completeness_results.append(daily_counts)

# Combine all dataset-level daily completeness checks into one table.
daily_completeness_df = (
    pd.concat(daily_completeness_results, ignore_index=True)
    .sort_values(["dataset", "delivery_date"])
    .reset_index(drop=True)
)

display(daily_completeness_df)

    delivery_date  mtu_minutes  row_count  unique_timestamp_count    dataset  expected_intervals dst_day_type  actual_interval_count             count_basis  is_complete_day
0      2025-11-01           15         95                      95  balancing                  96   normal_day                     95  unique_timestamp_count            False
1      2025-11-02           15         96                      96  balancing                  96   normal_day                     96  unique_timestamp_count             True
2      2025-11-03           15         96                      96  balancing                  96   normal_day                     96  unique_timestamp_count             True
3      2025-11-04           15         96                      96  balancing                  96   normal_day                     96  unique_timestamp_count             True
4      2025-11-05           15         96                      96  balancing                  96   normal_day                     96  unique_timestamp_count             True
..            ...          ...        ...                     ...        ...                 ...          ...                    ...                     ...              ...
693    2026-02-25           15         96                      96  imbalance                  96   normal_day                     96               row_count             True
694    2026-02-26           15         96                      96  imbalance                  96   normal_day                     96               row_count             True
695    2026-02-27           15         96                      96  imbalance                  96   normal_day                     96               row_count             True
696    2026-02-28           15         96                      96  imbalance                  96   normal_day                     96               row_count             True
697    2026-03-01           15          1                       1  imbalance                  96   normal_day                      1               row_count            False

[698 rows x 10 columns]

In [27]:
# Show all days where interval count does not match the expected count.
# These are the main completeness findings for Day 22.

incomplete_days = daily_completeness_df[
    daily_completeness_df["is_complete_day"] == False
].copy()

display(incomplete_days)

    delivery_date  mtu_minutes  row_count  unique_timestamp_count    dataset  expected_intervals dst_day_type  actual_interval_count             count_basis  is_complete_day
0      2025-11-01           15         95                      95  balancing                  96   normal_day                     95  unique_timestamp_count            False
120    2026-03-01           15          2                       1  balancing                  96   normal_day                      1  unique_timestamp_count            False
485    2025-12-31           15         95                      95    da_2025                  96   normal_day                     95               row_count            False
486    2026-01-01           15          1                       1    da_2025                  96   normal_day                      1               row_count            False
576    2026-04-01           15          1                       1    da_2026                  96   normal_day                      1               row_count            False
577    2025-11-01           15         95                      95  imbalance                  96   normal_day                     95               row_count            False
697    2026-03-01           15          1                       1  imbalance                  96   normal_day                      1               row_count            False

In [29]:
# Add boundary-day classification to separate partial file edges from true internal gaps.
# A partial first or last day is usually less serious than a missing interval inside the full coverage period.

dataset_boundaries = []

for dataset_name, df in datasets_with_mtu.items():
    dataset_boundaries.append({
        "dataset": dataset_name,
        "first_delivery_date": df["delivery_date"].min(),
        "last_delivery_date": df["delivery_date"].max(),
    })

dataset_boundaries_df = pd.DataFrame(dataset_boundaries)

daily_completeness_df = daily_completeness_df.merge(
    dataset_boundaries_df,
    on="dataset",
    how="left"
)

daily_completeness_df["is_boundary_day"] = (
    (daily_completeness_df["delivery_date"] == daily_completeness_df["first_delivery_date"]) |
    (daily_completeness_df["delivery_date"] == daily_completeness_df["last_delivery_date"])
)

daily_completeness_df["qa_status"] = np.select(
    [
        daily_completeness_df["is_complete_day"],
        (~daily_completeness_df["is_complete_day"]) & daily_completeness_df["is_boundary_day"],
        (~daily_completeness_df["is_complete_day"]) & (~daily_completeness_df["is_boundary_day"]),
    ],
    [
        "complete",
        "partial_boundary_day",
        "internal_incomplete_day",
    ],
    default="review"
)

display(daily_completeness_df)

,delivery_date,mtu_minutes,row_count,unique_timestamp_count,dataset,expected_intervals,dst_day_type,actual_interval_count,count_basis,is_complete_day,first_delivery_date,last_delivery_date,is_boundary_day,qa_status
0,2025-11-01,15,95,95,balancing,96,normal_day,95,unique_timestamp_count,False,2025-11-01,2026-03-01,True,partial_boundary_day
1,2025-11-02,15,96,96,balancing,96,normal_day,96,unique_timestamp_count,True,2025-11-01,2026-03-01,False,complete
2,2025-11-03,15,96,96,balancing,96,normal_day,96,unique_timestamp_count,True,2025-11-01,2026-03-01,False,complete
3,2025-11-04,15,96,96,balancing,96,normal_day,96,unique_timestamp_count,True,2025-11-01,2026-03-01,False,complete
4,2025-11-05,15,96,96,balancing,96,normal_day,96,unique_timestamp_count,True,2025-11-01,2026-03-01,False,complete
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693,2026-02-25,15,96,96,imbalance,96,normal_day,96,row_count,True,2025-11-01,2026-03-01,False,complete
694,2026-02-26,15,96,96,imbalance,96,normal_day,96,row_count,True,2025-11-01,2026-03-01,False,complete
695,2026-02-27,15,96,96,imbalance,96,normal_day,96,row_count,True,2025-11-01,2026-03-01,False,complete
696,2026-02-28,15,96,96,imbalance,96,normal_day,96,row_count,True,2025-11-01,2026-03-01,False,complete
697,2026-03-01,15,1,1,imbalance,96,normal_day,1,row_count,False,2025-11-01,2026-03-01,True,partial_boundary_day

In [30]:
# Show only non-complete days after boundary classification.
# Internal incomplete days are the most important QA problems.

qa_problem_days = daily_completeness_df[
    daily_completeness_df["qa_status"] != "complete"
].copy()

display(
    qa_problem_days[
        [
            "dataset",
            "delivery_date",
            "mtu_minutes",
            "row_count",
            "unique_timestamp_count",
            "actual_interval_count",
            "expected_intervals",
            "count_basis",
            "dst_day_type",
            "is_boundary_day",
            "qa_status",
        ]
    ]
)

       dataset delivery_date  mtu_minutes  row_count  unique_timestamp_count  actual_interval_count  expected_intervals             count_basis dst_day_type  is_boundary_day                qa_status
0    balancing    2025-11-01           15         95                      95                     95                  96  unique_timestamp_count   normal_day             True     partial_boundary_day
120  balancing    2026-03-01           15          2                       1                      1                  96  unique_timestamp_count   normal_day             True     partial_boundary_day
485    da_2025    2025-12-31           15         95                      95                     95                  96               row_count   normal_day            False  internal_incomplete_day
486    da_2025    2026-01-01           15          1                       1                      1                  96               row_count   normal_day             True     partial_boundary_day
576    da_2026    2026-04-01           15          1                       1                      1                  96               row_count   normal_day             True     partial_boundary_day
577  imbalance    2025-11-01           15         95                      95                     95                  96               row_count   normal_day             True     partial_boundary_day
697  imbalance    2026-03-01           15          1                       1                      1                  96               row_count   normal_day             True     partial_boundary_day

In [28]:
# Inspect DST transition days directly.
# This confirms whether March and October DST behavior is handled correctly.

dst_days_to_check = [
    pd.Timestamp("2025-03-30").date(),
    pd.Timestamp("2025-10-26").date(),
    pd.Timestamp("2026-03-29").date(),
    pd.Timestamp("2026-10-25").date(),
]

dst_check = daily_completeness_df[
    daily_completeness_df["delivery_date"].isin(dst_days_to_check)
].copy()

display(dst_check)

    delivery_date  mtu_minutes  row_count  unique_timestamp_count  dataset  expected_intervals    dst_day_type  actual_interval_count count_basis  is_complete_day
209    2025-03-30           60         23                      23  da_2025                  23  spring_dst_day                     23   row_count             True
419    2025-10-26           15        100                      96  da_2025                 100  autumn_dst_day                    100   row_count             True
573    2026-03-29           15         92                      92  da_2026                  92  spring_dst_day                     92   row_count             True

In [18]:
# Show timestamps for the 2025 spring DST day in DA 2025.
# Because DA 2025 is hourly in March, we expect 23 rows and no 02:00 timestamp.

da_2025 = datasets_with_mtu["da_2025"]

spring_2025 = (
    da_2025[da_2025["delivery_date"] == pd.Timestamp("2025-03-30").date()]
    .sort_values("timestamp")
    .reset_index(drop=True)
)

spring_2025_times = spring_2025[["timestamp", "price_eur_mwh", "mtu_minutes"]].copy()
spring_2025_times["clock_time"] = spring_2025_times["timestamp"].dt.strftime("%H:%M")

print("Rows on 2025-03-30:", len(spring_2025_times))
display(spring_2025_times)

Rows on 2025-03-30: 23

             timestamp  price_eur_mwh  mtu_minutes clock_time
0  2025-03-30 00:00:00          46.22           60      00:00
1  2025-03-30 01:00:00          15.88           60      01:00
2  2025-03-30 03:00:00           5.09           60      03:00
3  2025-03-30 04:00:00           1.20           60      04:00
4  2025-03-30 05:00:00           0.09           60      05:00
5  2025-03-30 06:00:00           0.93           60      06:00
6  2025-03-30 07:00:00           0.99           60      07:00
7  2025-03-30 08:00:00           1.45           60      08:00
8  2025-03-30 09:00:00           0.09           60      09:00
9  2025-03-30 10:00:00          -0.76           60      10:00
10 2025-03-30 11:00:00          -3.80           60      11:00
11 2025-03-30 12:00:00         -15.40           60      12:00
12 2025-03-30 13:00:00         -22.76           60      13:00
13 2025-03-30 14:00:00         -22.92           60      14:00
14 2025-03-30 15:00:00         -11.74           60      15:00
15 2025-03-30 16:00:00          -3.96           60      16:00
16 2025-03-30 17:00:00           0.24           60      17:00
17 2025-03-30 18:00:00          38.10           60      18:00
18 2025-03-30 19:00:00          92.00           60      19:00
19 2025-03-30 20:00:00          92.13           60      20:00
20 2025-03-30 21:00:00          86.44           60      21:00
21 2025-03-30 22:00:00          82.88           60      22:00
22 2025-03-30 23:00:00          54.14           60      23:00

In [19]:
# Show duplicate timestamps on the 2025 autumn DST day in DA 2025.
# Because the clock moves back, the 02:00 hour repeats in local time.

autumn_2025 = (
    da_2025[da_2025["delivery_date"] == pd.Timestamp("2025-10-26").date()]
    .sort_values("timestamp")
    .reset_index(drop=True)
)

autumn_2025_duplicates = (
    autumn_2025[autumn_2025["timestamp"].duplicated(keep=False)]
    .sort_values("timestamp")
    .reset_index(drop=True)
)

print("Rows on 2025-10-26:", len(autumn_2025))
print("Duplicate timestamp rows on 2025-10-26:", len(autumn_2025_duplicates))

display(autumn_2025_duplicates)

Rows on 2025-10-26: 100
Duplicate timestamp rows on 2025-10-26: 8

            timestamp  price_eur_mwh  mtu_minutes delivery_date
0 2025-10-26 02:00:00          75.33           15    2025-10-26
1 2025-10-26 02:00:00          63.05           15    2025-10-26
2 2025-10-26 02:15:00          65.54           15    2025-10-26
3 2025-10-26 02:15:00          67.41           15    2025-10-26
4 2025-10-26 02:30:00          60.01           15    2025-10-26
5 2025-10-26 02:30:00          63.93           15    2025-10-26
6 2025-10-26 02:45:00          53.67           15    2025-10-26
7 2025-10-26 02:45:00          58.91           15    2025-10-26

## DST findings

The DA 2025 file correctly reflects the spring DST transition on 2025-03-30.  
Because the file is hourly in March 2025, the expected count is 23 intervals instead of 24.

The DA 2025 file also contains duplicate local timestamps around the autumn DST transition on 2025-10-26.  
This is expected because the clock moves back from 03:00 to 02:00 and the 02:00 hour repeats.

For 15-minute data:
- normal day = 96 intervals,
- spring DST day = 92 intervals,
- autumn DST day = 100 intervals.

DST-related duplicates are not automatically data-quality errors.

In [20]:
# Identify missing timestamp occurrences for incomplete days.
# This is useful when a daily count is lower than expected.

missing_interval_results = []

for dataset_name, df in datasets_with_mtu.items():
    config = DATASET_CONFIG[dataset_name]
    count_method = config["interval_count_method"]

    dataset_incomplete_days = incomplete_days[
        incomplete_days["dataset"] == dataset_name
    ]

    for _, day_row in dataset_incomplete_days.iterrows():
        delivery_date = day_row["delivery_date"]
        mtu_minutes = int(day_row["mtu_minutes"])

        day_data = df[df["delivery_date"] == delivery_date].copy()

        expected_counts = expected_timestamp_occurrences_for_day(delivery_date, mtu_minutes)

        if count_method == "rows":
            actual_counts = (
                day_data
                .value_counts("timestamp")
                .reset_index(name="actual_occurrences")
            )
        else:
            actual_counts = (
                day_data[["timestamp"]]
                .drop_duplicates()
                .value_counts("timestamp")
                .reset_index(name="actual_occurrences")
            )

        comparison = expected_counts.merge(
            actual_counts,
            on="timestamp",
            how="left"
        )

        comparison["actual_occurrences"] = comparison["actual_occurrences"].fillna(0).astype(int)
        comparison["missing_occurrences"] = comparison["expected_occurrences"] - comparison["actual_occurrences"]

        missing = comparison[comparison["missing_occurrences"] > 0].copy()
        missing["dataset"] = dataset_name
        missing["delivery_date"] = delivery_date
        missing["mtu_minutes"] = mtu_minutes
        missing["count_method"] = count_method

        missing_interval_results.append(missing)

if missing_interval_results:
    missing_intervals_df = (
        pd.concat(missing_interval_results, ignore_index=True)
        .sort_values(["dataset", "timestamp"])
        .reset_index(drop=True)
    )
else:
    missing_intervals_df = pd.DataFrame()

display(missing_intervals_df)

              timestamp  expected_occurrences  actual_occurrences  missing_occurrences    dataset delivery_date  mtu_minutes       count_method
0   2025-11-01 00:00:00                     1                   0                    1  balancing    2025-11-01           15  unique_timestamps
1   2026-03-01 00:15:00                     1                   0                    1  balancing    2026-03-01           15  unique_timestamps
2   2026-03-01 00:30:00                     1                   0                    1  balancing    2026-03-01           15  unique_timestamps
3   2026-03-01 00:45:00                     1                   0                    1  balancing    2026-03-01           15  unique_timestamps
4   2026-03-01 01:00:00                     1                   0                    1  balancing    2026-03-01           15  unique_timestamps
..                  ...                   ...                 ...                  ...        ...           ...          ...                ...
378 2026-03-01 22:45:00                     1                   0                    1  imbalance    2026-03-01           15               rows
379 2026-03-01 23:00:00                     1                   0                    1  imbalance    2026-03-01           15               rows
380 2026-03-01 23:15:00                     1                   0                    1  imbalance    2026-03-01           15               rows
381 2026-03-01 23:30:00                     1                   0                    1  imbalance    2026-03-01           15               rows
382 2026-03-01 23:45:00                     1                   0                    1  imbalance    2026-03-01           15               rows

[383 rows x 8 columns]

In [21]:
# Combine DA 2025 and DA 2026 data for overlap checks with imbalance data.
# Source file is kept so boundary overlaps can be investigated.

da_all = pd.concat(
    [
        datasets["da_2025"].assign(source_file="da_prices_si_2025_clean.csv"),
        datasets["da_2026"].assign(source_file="da_prices_si_clean.csv"),
    ],
    ignore_index=True
)

da_all = da_all.sort_values("timestamp").reset_index(drop=True)

# Drop duplicate DA timestamps for join checks.
# keep="last" gives priority to the 2026 file where the annual boundary overlaps.
da_unique = da_all.drop_duplicates(subset=["timestamp"], keep="last").copy()

imbalance = datasets["imbalance"].copy()

# Find imbalance timestamps that are not present in DA.
unmatched_imbalance = imbalance[
    ~imbalance["timestamp"].isin(da_unique["timestamp"])
].copy()

print("DA all rows:", len(da_all))
print("DA unique timestamp rows:", len(da_unique))
print("Imbalance rows:", len(imbalance))
print("Unmatched imbalance rows:", len(unmatched_imbalance))

display(unmatched_imbalance)

DA all rows: 23928
DA unique timestamp rows: 23923
Imbalance rows: 11520
Unmatched imbalance rows: 1

      timestamp  imbalance_price_pos  imbalance_price_neg  sipx              settlement_type
5759 2025-12-31               112.79               112.79  77.8  Second imbalance settlement

## DA + imbalance timestamp mismatch

The DA and imbalance datasets mostly align in the overlapping period.

A previous cross-dataset check showed:
- 11,519 DA rows in the overlap,
- 11,520 imbalance rows,
- 11,519 joined rows.

The one unmatched imbalance row is caused by a missing DA timestamp.

This is a real QA finding because it affects cross-dataset analysis.  
Any DA + imbalance analysis should either exclude this unmatched row or clearly document that the analysis uses matched timestamps only.

In [22]:
# Check important numeric columns for negative values, zeros, and high values.
# Negative prices and spikes can be valid in power markets, so this flags values for review, not automatic deletion.

value_check_results = []

for dataset_name, df in datasets.items():
    config = DATASET_CONFIG[dataset_name]

    columns_to_check = []
    columns_to_check.extend(config.get("price_columns", []))
    columns_to_check.extend(config.get("important_columns", []))

    # Keep only numeric columns that exist in the dataset.
    columns_to_check = [
        col for col in dict.fromkeys(columns_to_check)
        if col in df.columns and pd.api.types.is_numeric_dtype(df[col])
    ]

    for col in columns_to_check:
        value_check_results.append({
            "dataset": dataset_name,
            "column": col,
            "rows": len(df),
            "min": df[col].min(),
            "p01": df[col].quantile(0.01),
            "mean": df[col].mean(),
            "median": df[col].median(),
            "p99": df[col].quantile(0.99),
            "max": df[col].max(),
            "negative_count": (df[col] < 0).sum(),
            "zero_count": (df[col] == 0).sum(),
            "above_500_count": (df[col] > 500).sum(),
        })

value_checks_df = pd.DataFrame(value_check_results)

display(value_checks_df)

      dataset               column   rows        min        p01         mean    median          p99         max  negative_count  zero_count  above_500_count
0     da_2025        price_eur_mwh  15387   -126.460    -2.0000   108.266467  105.2100    270.77840     561.750             269          62                5
1     da_2026        price_eur_mwh   8541    -69.920     0.0000   121.055885  118.0000    278.30400     400.760              84          12                0
2   imbalance  imbalance_price_pos  11520  -3285.020   -10.7710   121.935337  111.8100    375.79870    2745.440             204           5               36
3   imbalance  imbalance_price_neg  11520  -3285.020   -10.7710   121.935337  111.8100    375.79870    2745.440             204           5               36
4   imbalance                 sipx  11520     -0.440    43.4319   120.018549  112.5900    277.16340     400.760              14           5                0
5   balancing         aFRR EUR/MWh  20160      0.000     0.0000   149.266044  167.8500    392.29000     579.330               0        4974               40
6   balancing         mFRR EUR/MWh  20160      0.000     0.0000     3.692448    0.0000      0.00000    3293.270               0       20124               36
7   balancing        VoAA+ EUR/MWh  20160      0.000     0.0000     0.015704    0.0000      0.00000     158.300               0       20158                0
8   balancing        VoAA- EUR/MWh  20160      0.000     0.0000     0.008879    0.0000      0.00000      89.500               0       20158                0
9   balancing             Wpos MWh  20160      0.000     0.0270    10.144370    5.8090     59.63558     135.782               0         113                0
10  balancing             Wneg MWh  20160   -124.446   -53.8600   -10.344734   -7.0225     -0.03659       0.000           20088          72                0
11  balancing             Spos EUR  20160   -719.400     0.0000  1402.573758  460.0400  13756.81510  155317.860             103         251             9708
12  balancing             Sneg EUR  20160 -24020.450 -4944.0100  -668.631251 -320.1500    230.41000   79004.810           19718         155              129

In [23]:
# Show rows where price-like columns are negative, zero, or above 500.
# This is used for inspection only; these values may be valid market outcomes.

extreme_price_rows = []

for dataset_name, df in datasets.items():
    config = DATASET_CONFIG[dataset_name]

    for col in config.get("price_columns", []):
        if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
            flagged = df[
                (df[col] < 0) |
                (df[col] == 0) |
                (df[col] > 500)
            ].copy()

            if len(flagged) > 0:
                flagged["dataset"] = dataset_name
                flagged["checked_column"] = col
                flagged["checked_value"] = flagged[col]

                keep_cols = ["dataset", "timestamp", "checked_column", "checked_value"]

                if "settlement_type" in flagged.columns:
                    keep_cols.append("settlement_type")

                extreme_price_rows.append(flagged[keep_cols])

if extreme_price_rows:
    extreme_price_rows_df = (
        pd.concat(extreme_price_rows, ignore_index=True)
        .sort_values(["dataset", "timestamp", "checked_column"])
        .reset_index(drop=True)
    )
else:
    extreme_price_rows_df = pd.DataFrame()

display(extreme_price_rows_df.head(200))
print("Total flagged price rows:", len(extreme_price_rows_df))

       dataset           timestamp checked_column  checked_value              settlement_type
0    balancing 2025-11-01 00:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
1    balancing 2025-11-01 00:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
2    balancing 2025-11-01 00:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
3    balancing 2025-11-01 00:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
4    balancing 2025-11-01 00:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
5    balancing 2025-11-01 00:30:00   aFRR EUR/MWh            0.0  Second imbalance settlement
6    balancing 2025-11-01 00:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
7    balancing 2025-11-01 00:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
8    balancing 2025-11-01 00:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
9    balancing 2025-11-01 00:45:00   aFRR EUR/MWh            0.0  Second imbalance settlement
10   balancing 2025-11-01 00:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
11   balancing 2025-11-01 01:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
12   balancing 2025-11-01 01:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
13   balancing 2025-11-01 01:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
14   balancing 2025-11-01 01:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
15   balancing 2025-11-01 01:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
16   balancing 2025-11-01 01:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
17   balancing 2025-11-01 01:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
18   balancing 2025-11-01 01:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
19   balancing 2025-11-01 01:30:00   aFRR EUR/MWh            0.0  Second imbalance settlement
20   balancing 2025-11-01 01:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
21   balancing 2025-11-01 01:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
22   balancing 2025-11-01 01:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
23   balancing 2025-11-01 01:45:00   aFRR EUR/MWh            0.0  Second imbalance settlement
24   balancing 2025-11-01 01:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
25   balancing 2025-11-01 02:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
26   balancing 2025-11-01 02:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
27   balancing 2025-11-01 02:00:00   aFRR EUR/MWh            0.0  Second imbalance settlement
28   balancing 2025-11-01 02:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
29   balancing 2025-11-01 02:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
30   balancing 2025-11-01 02:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
31   balancing 2025-11-01 02:15:00   aFRR EUR/MWh            0.0  Second imbalance settlement
32   balancing 2025-11-01 02:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
33   balancing 2025-11-01 02:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
34   balancing 2025-11-01 02:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
35   balancing 2025-11-01 02:30:00   aFRR EUR/MWh            0.0  Second imbalance settlement
36   balancing 2025-11-01 02:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
37   balancing 2025-11-01 02:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
38   balancing 2025-11-01 02:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
39   balancing 2025-11-01 02:45:00   aFRR EUR/MWh            0.0  Second imbalance settlement
40   balancing 2025-11-01 02:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
41   balancing 2025-11-01 03:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
42   balancing 2025-11-01 03:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
43   balancing 2025-11-01 03:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
44   balancing 2025-11-01 03:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
45   balancing 2025-11-01 03:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
46   balancing 2025-11-01 03:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
47   balancing 2025-11-01 03:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
48   balancing 2025-11-01 03:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
49   balancing 2025-11-01 03:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
50   balancing 2025-11-01 03:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
51   balancing 2025-11-01 03:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
52   balancing 2025-11-01 03:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
53   balancing 2025-11-01 04:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
54   balancing 2025-11-01 04:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
55   balancing 2025-11-01 04:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
56   balancing 2025-11-01 04:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
57   balancing 2025-11-01 04:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
58   balancing 2025-11-01 04:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
59   balancing 2025-11-01 04:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
60   balancing 2025-11-01 04:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
61   balancing 2025-11-01 04:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
62   balancing 2025-11-01 04:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
63   balancing 2025-11-01 04:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
64   balancing 2025-11-01 04:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
65   balancing 2025-11-01 05:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
66   balancing 2025-11-01 05:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
67   balancing 2025-11-01 05:00:00   aFRR EUR/MWh            0.0  Second imbalance settlement
68   balancing 2025-11-01 05:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
69   balancing 2025-11-01 05:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
70   balancing 2025-11-01 05:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
71   balancing 2025-11-01 05:15:00   aFRR EUR/MWh            0.0  Second imbalance settlement
72   balancing 2025-11-01 05:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
73   balancing 2025-11-01 05:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
74   balancing 2025-11-01 05:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
75   balancing 2025-11-01 05:30:00   aFRR EUR/MWh            0.0  Second imbalance settlement
76   balancing 2025-11-01 05:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
77   balancing 2025-11-01 05:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
78   balancing 2025-11-01 05:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
79   balancing 2025-11-01 05:45:00   aFRR EUR/MWh            0.0  Second imbalance settlement
80   balancing 2025-11-01 05:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
81   balancing 2025-11-01 06:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
82   balancing 2025-11-01 06:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
83   balancing 2025-11-01 06:00:00   aFRR EUR/MWh            0.0  Second imbalance settlement
84   balancing 2025-11-01 06:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
85   balancing 2025-11-01 06:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
86   balancing 2025-11-01 06:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
87   balancing 2025-11-01 06:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
88   balancing 2025-11-01 06:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
89   balancing 2025-11-01 06:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
90   balancing 2025-11-01 06:30:00   aFRR EUR/MWh            0.0  Second imbalance settlement
91   balancing 2025-11-01 06:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
92   balancing 2025-11-01 06:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
93   balancing 2025-11-01 06:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
94   balancing 2025-11-01 06:45:00   aFRR EUR/MWh            0.0  Second imbalance settlement
95   balancing 2025-11-01 06:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
96   balancing 2025-11-01 07:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
97   balancing 2025-11-01 07:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
98   balancing 2025-11-01 07:00:00   aFRR EUR/MWh            0.0  Second imbalance settlement
99   balancing 2025-11-01 07:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
100  balancing 2025-11-01 07:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
101  balancing 2025-11-01 07:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
102  balancing 2025-11-01 07:15:00   aFRR EUR/MWh            0.0  Second imbalance settlement
103  balancing 2025-11-01 07:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
104  balancing 2025-11-01 07:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
105  balancing 2025-11-01 07:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
106  balancing 2025-11-01 07:30:00   aFRR EUR/MWh            0.0  Second imbalance settlement
107  balancing 2025-11-01 07:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
108  balancing 2025-11-01 07:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
109  balancing 2025-11-01 07:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
110  balancing 2025-11-01 07:45:00   aFRR EUR/MWh            0.0  Second imbalance settlement
111  balancing 2025-11-01 07:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
112  balancing 2025-11-01 08:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
113  balancing 2025-11-01 08:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
114  balancing 2025-11-01 08:00:00   aFRR EUR/MWh            0.0  Second imbalance settlement
115  balancing 2025-11-01 08:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
116  balancing 2025-11-01 08:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
117  balancing 2025-11-01 08:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
118  balancing 2025-11-01 08:15:00   aFRR EUR/MWh            0.0  Second imbalance settlement
119  balancing 2025-11-01 08:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
120  balancing 2025-11-01 08:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
121  balancing 2025-11-01 08:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
122  balancing 2025-11-01 08:30:00   aFRR EUR/MWh            0.0  Second imbalance settlement
123  balancing 2025-11-01 08:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
124  balancing 2025-11-01 08:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
125  balancing 2025-11-01 08:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
126  balancing 2025-11-01 08:45:00   aFRR EUR/MWh            0.0  Second imbalance settlement
127  balancing 2025-11-01 08:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
128  balancing 2025-11-01 09:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
129  balancing 2025-11-01 09:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
130  balancing 2025-11-01 09:00:00   aFRR EUR/MWh            0.0  Second imbalance settlement
131  balancing 2025-11-01 09:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
132  balancing 2025-11-01 09:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
133  balancing 2025-11-01 09:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
134  balancing 2025-11-01 09:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
135  balancing 2025-11-01 09:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
136  balancing 2025-11-01 09:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
137  balancing 2025-11-01 09:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
138  balancing 2025-11-01 09:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
139  balancing 2025-11-01 09:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
140  balancing 2025-11-01 09:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
141  balancing 2025-11-01 10:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
142  balancing 2025-11-01 10:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
143  balancing 2025-11-01 10:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
144  balancing 2025-11-01 10:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
145  balancing 2025-11-01 10:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
146  balancing 2025-11-01 10:15:00   aFRR EUR/MWh            0.0  Second imbalance settlement
147  balancing 2025-11-01 10:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
148  balancing 2025-11-01 10:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
149  balancing 2025-11-01 10:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
150  balancing 2025-11-01 10:30:00   aFRR EUR/MWh            0.0  Second imbalance settlement
151  balancing 2025-11-01 10:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
152  balancing 2025-11-01 10:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
153  balancing 2025-11-01 10:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
154  balancing 2025-11-01 10:45:00   aFRR EUR/MWh            0.0  Second imbalance settlement
155  balancing 2025-11-01 10:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
156  balancing 2025-11-01 11:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
157  balancing 2025-11-01 11:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
158  balancing 2025-11-01 11:00:00   aFRR EUR/MWh            0.0  Second imbalance settlement
159  balancing 2025-11-01 11:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
160  balancing 2025-11-01 11:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
161  balancing 2025-11-01 11:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
162  balancing 2025-11-01 11:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
163  balancing 2025-11-01 11:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
164  balancing 2025-11-01 11:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
165  balancing 2025-11-01 11:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
166  balancing 2025-11-01 11:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
167  balancing 2025-11-01 11:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
168  balancing 2025-11-01 11:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
169  balancing 2025-11-01 12:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
170  balancing 2025-11-01 12:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
171  balancing 2025-11-01 12:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
172  balancing 2025-11-01 12:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
173  balancing 2025-11-01 12:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
174  balancing 2025-11-01 12:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
175  balancing 2025-11-01 12:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
176  balancing 2025-11-01 12:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
177  balancing 2025-11-01 12:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
178  balancing 2025-11-01 12:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
179  balancing 2025-11-01 12:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
180  balancing 2025-11-01 12:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
181  balancing 2025-11-01 13:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
182  balancing 2025-11-01 13:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
183  balancing 2025-11-01 13:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
184  balancing 2025-11-01 13:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
185  balancing 2025-11-01 13:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
186  balancing 2025-11-01 13:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement
187  balancing 2025-11-01 13:30:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
188  balancing 2025-11-01 13:30:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
189  balancing 2025-11-01 13:30:00   aFRR EUR/MWh            0.0  Second imbalance settlement
190  balancing 2025-11-01 13:30:00   mFRR EUR/MWh            0.0  Second imbalance settlement
191  balancing 2025-11-01 13:45:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
192  balancing 2025-11-01 13:45:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
193  balancing 2025-11-01 13:45:00   mFRR EUR/MWh            0.0  Second imbalance settlement
194  balancing 2025-11-01 14:00:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
195  balancing 2025-11-01 14:00:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
196  balancing 2025-11-01 14:00:00   mFRR EUR/MWh            0.0  Second imbalance settlement
197  balancing 2025-11-01 14:15:00  VoAA+ EUR/MWh            0.0  Second imbalance settlement
198  balancing 2025-11-01 14:15:00  VoAA- EUR/MWh            0.0  Second imbalance settlement
199  balancing 2025-11-01 14:15:00   mFRR EUR/MWh            0.0  Second imbalance settlement

Total flagged price rows: 66431

## Value range findings

The value range check flags:
- negative values,
- zero values,
- values above 500.

For DA and imbalance prices, negative prices and spikes can be valid electricity-market outcomes.  
They are not automatically data errors.

For balancing volumes and costs, zeros are common because not every balancing product is activated in every interval.  
Negative values may also be meaningful depending on direction and settlement logic.

Outlier treatment should be handled separately in a later analysis step.

In [24]:
# Build a final compact QA summary table for Day 22.
# This gives a high-level status per dataset.

final_qa_summary = []

for dataset_name, df in datasets.items():
    dataset_incomplete = daily_completeness_df[
        daily_completeness_df["dataset"] == dataset_name
    ]

    final_qa_summary.append({
        "dataset": dataset_name,
        "rows": len(df),
        "first_timestamp": df["timestamp"].min(),
        "last_timestamp": df["timestamp"].max(),
        "null_values": df.isna().sum().sum(),
        "duplicate_timestamps": df["timestamp"].duplicated().sum(),
        "incomplete_days": (dataset_incomplete["is_complete_day"] == False).sum(),
        "spring_dst_days_checked": (dataset_incomplete["dst_day_type"] == "spring_dst_day").sum(),
        "autumn_dst_days_checked": (dataset_incomplete["dst_day_type"] == "autumn_dst_day").sum(),
    })

final_qa_summary_df = pd.DataFrame(final_qa_summary)

display(final_qa_summary_df)

     dataset   rows     first_timestamp last_timestamp  null_values  duplicate_timestamps  incomplete_days  spring_dst_days_checked  autumn_dst_days_checked
0    da_2025  15387 2025-01-01 00:00:00     2026-01-01            0                     4                2                        1                        1
1    da_2026   8541 2026-01-01 00:00:00     2026-04-01            0                     0                1                        1                        0
2  imbalance  11520 2025-11-01 00:15:00     2026-03-01            0                     0                2                        0                        0
3  balancing  20160 2025-11-01 00:15:00     2026-03-01            0                  8640                2                        0                        0

## Day 22 QA conclusion

The curated datasets are structurally usable for analysis.  
Timestamps are parsed correctly and the loaded datasets contain no null values.

Important findings:

1. The 2025 DA file has mixed MTU resolution:
   - 60-minute before 2025-10-01,
   - 15-minute from 2025-10-01 onward.
   This is expected and reflects the Slovenian day-ahead market-rule transition.

2. DST checks must be resolution-aware:
   - normal hourly day: 24 intervals,
   - spring DST hourly day: 23 intervals,
   - autumn DST hourly day: 25 intervals,
   - normal 15-minute day: 96 intervals,
   - spring DST 15-minute day: 92 intervals,
   - autumn DST 15-minute day: 100 intervals.

3. DA 2025 duplicate timestamps are linked to autumn DST repeated local timestamps and should not be removed automatically.

4. Borzen imbalance and balancing data must be interpreted with `settlement_type`.

5. The DA + imbalance overlap has one unmatched imbalance timestamp caused by a missing DA timestamp.

6. Boundary days and incomplete days must be documented before using daily summaries or joins.

7. Negative prices, zeros, and spikes are flagged for review, but they are not automatically data errors in electricity-market data.

Overall, the data is suitable for continued analysis if future joins, daily summaries, and visualizations remain MTU-aware, DST-aware, and explicit about incomplete periods.